### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by dustinlacewell** [doug/rendercan#1]
Unchecked runtime.lastError: Cannot access contents of url "https://arkounay.github.io/2D-Canvas-Image-Particles/". Extension manifest must request permission to access this host.
_generated_background_page.html:1 Error handling response: TypeError: Cannot read property '0' of undefined
    at chrome-extension://enlfmgpmfaibbeoelliknejffljklemg/background.js:115:18

**Comment by doug** [comment]
No longer maintaining this will update a deprecation warning and remove it. Suggest migrating to https://github.com/spite/ccapture.js/

**Comment by dustinlacewell** [comment]
Thanks.
